### ISSUE TITLE
Badge doesn't hide after route change(SPA)

### ISSUE THREAD

**Issue by muneebkq** [abinnovision/recaptcha-v3#744]
When the `badge` prop is modified to `bottomleft` when the route is changed to a different point Recaptcha badge doesn't hide

**Comment by WipeAir** [comment]
This behaviour is intentional as the `badge` property will be passed to the `render` function of reCAPTCHA. After it has been rendered once, it's not possible to re-render it. Also reCAPTCHA v3 is intended to be active throughout whole time the user is using your site.

You may also look into hiding the badge using the `hideBadge` function when it's not needed.
